# Generated by Django 5.2.9 on 2025-12-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('prediction_burnout_risk', models.FloatField()),
                ('predicted_burnout_level', models.CharField(max_length=50)),
                ('contributing_factors', models.TextField()),
                ('recommendations', models.TextField()),
                ('meditation_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_state', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_latitude', models.FloatField(blank=True, null=True)),
                ('birth_longitude', models.FloatField(blank=True, null=True)),
                ('birth_timezone', models.FloatField(blank=True, null=True)),
                ('wearable_device_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_burnout_risk', models.BooleanField(default=True)),
                ('notify_astrological_events', models.BooleanField(default=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('preferred_notification_method', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('App', 'App Notification')], default='Email', max_length=50)),
                ('device_sync_enabled', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language_preference', models.CharField(default='English', max_length=50)),
                ('astrology_opt_in', models.BooleanField(default=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('feature_requests', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_email', models.EmailField(max_length=254)),
                ('access_level', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('can_receive_alerts', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_sign', models.CharField(max_length=50)),
                ('moon_sign', models.CharField(max_length=50)),
                ('rising_sign', models.CharField(max_length=50)),
                ('key_aspects', models.TextField()),
                ('houses', models.TextField()),
                ('generated_chart_url', models.URLField(blank=True, null=True)),
                ('raw_chart_data', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('hrv_score', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('activity_level', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('sleep_duration', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AstrologicalTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_date', models.DateField()),
                ('transit_planet', models.CharField(max_length=50)),
                ('natal_house', models.CharField(default='1st', max_length=50)),
                ('ruled_houses', models.CharField(default='1st', max_length=50)),
                ('interpretation', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_message', models.TextField()),
                ('burnout_percentage', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aiprediction')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
